export const githubKeysLevel = {
  NONE: 'NONE',
  FIRST_QUARTILE: 'FIRST_QUARTILE',
  SECOND_QUARTILE: 'SECOND_QUARTILE',
  THIRD_QUARTILE: 'THIRD_QUARTILE',
  FOURTH_QUARTILE: 'FOURTH_QUARTILE',
} as const;
